version: "3"
services:
  mongo:
    container_name: rpa-mongo
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - rpa-mongo-volume:/data/db
    ports:
      - "27020:27017"
    networks:
      - rpa-network

  backend:
    container_name: rpa-backend
    networks:
      - rpa-network
    build:
      context: ../backend
      dockerfile: Dockerfile
    environment:
      - SIREN_API_KEY=0e8e57f5-3a90-3844-ad19-05f66c6cecf3
      - MONGO_URL=mongodb://rpa-mongo/rpaDataCollectorDB
    ports:
      - "3020:3000"

  frontend:
    container_name: rpa-frontend
    networks:
      - rpa-network
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "4220:4200"

networks:
  rpa-network:
    driver: bridge

volumes:
  rpa-mongo-volume:
